### ISSUE TITLE
Download vswhere if missing

### ISSUE THREAD

**Issue by aminya** [MarkSchofield/Toolchain#11]
It would be nice to automate downloading the vswhere.exe if it is not found on the system.

**Comment by MarkSchofield** [comment]
Yes, definitely. I added support to download `ninja.exe` if it's not found or specified. I think the next step would be to apply similar logic to get `nuget.exe`. And then use that to download `vswhere` (which ships in a NuGet).

**Comment by MarkSchofield** [comment]
Ah, `vswhere.exe` also ships as a GitHub Release Assert - for example: https://github.com/microsoft/vswhere/releases/download/2.8.4/vswhere.exe. It could be downloaded from there without a `nuget.exe` dependency.

**Comment by aminya** [comment]
Yes, I think a `file(DOWNLOAD )` call would do it.

**Comment by MarkSchofield** [comment]
Fixed with #16.
