### ISSUE TITLE
Consider not using GIT LFS for the examples or in a release branch.

### ISSUE THREAD

**Issue by aminya** [MarkSchofield/Toolchain#17]
CMake's FetchContent is slow to download this repository because of its use of Git LFS. 
https://github.com/MarkSchofield/Toolchain/search?q=lfs

Another solution is to use a release branch that deletes the whole examples folder. I have been maintaining a release branch to work around this. 
https://github.com/aminya/Toolchain/tree/release

**Comment by MarkSchofield** [comment]
I'd rather keep the examples so that there's something to build for - say - a CI build, if I get around to setting one up. Would zipped content associated with a release work?

**Comment by MarkSchofield** [comment]
Although, if the Toolchain repo was minimally sufficient, then it would probably be more amenable to submoduleing, which I'd find handy as a consumption model. Then the examples could move to a, say, ToolchainExamples repo that would submodule Toolchain. Ideas?

**Comment by aminya** [comment]
If you also want to support Git submodules, then I think having a release branch is the way to go.
- People can speed up downloading via CMake FetchContent by referencing the URL of the release branch
- It also allows people to use the branch feature of Git submodules to speed up cloning.
