### ISSUE TITLE
Toolchain shouldn't update 'CMAKE_MODULE_PATH'

### ISSUE THREAD

**Issue by MarkSchofield** [MarkSchofield/Toolchain#29]
The toolchain files update CMAKE_MODULE_PATH so that 'opt-in' functionality can be included - such as IDL support. But by updating the CMAKE_MODULE_PATH the chance of colliding/breaking consuming builds in-advertently seems higher. Alternatives:
1. Set a variable allowing consumers to, say:

```cmake
include(${TOOLCHAIN_SUPPORT}/MidlRT)
```

instead of:

```cmake
include(MidlRT)
```

2. Include all functionality in the toolchain by default. If the '.cmake' files are less intrusive (as recommended by #18), then making the support 'opt-in' may not be necessary.

**Comment by aminya** [comment]
You can use what I did for `project_options`:

https://github.com/aminya/project_options/blob/49de1cc71e544bf56aa3a83768e044040a8726c2/src/Index.cmake#L13-L16
