### ISSUE TITLE
Value of CPPWINRT_PROJECTION_ROOT_PATH is not exported from generate_winrt_projection

### ISSUE THREAD

**Issue by dfields-msft** [MarkSchofield/Toolchain#30]
I think this line needs to be duplicated with PARENT_SCOPE so the caller of `generate_winrt_projection` can access the value of `CPPWINRT_PROJECTION_ROOT_PATH`. At least, when I tried this locally, it didn't work without that. (That said, the more holistic changes proposed by #27 sound like a better investment and may supersede this.)

https://github.com/MarkSchofield/Toolchain/blob/c789b4b58f995cb401f2f290447c3d0c4fd6c91b/Support/CppWinRT.cmake#L54

**Comment by MarkSchofield** [comment]
Ah, yes, you're right. Whenever I'm using `generate_winrt_projection`, I explicitly set `CPPWINRT_PROJECTION_ROOT_PATH`, so already know it outside of `generate_winrt_projection`. If you're relying on the default, then it would need to be set.

**Comment by dfields-msft** [comment]
Yeah, that's probably more useful than relying on the default anyway; I was following along with the example project to get bootstrapped and tripped on this. I suspect the example project may inadvertently be compiling against SDK winrt headers rather than the ones generated by CMake... (haven't checked out this repo and tried it personally though).

**Comment by MarkSchofield** [comment]
The `example` code did a heavy-handed:

```cmake
include_directories(BEFORE SYSTEM ${CPPWINRT_PROJECTION_ROOT_PATH})
```

To force the C++/WinRT projection into the start of the SYSTEM includes for everything. So I believe it was working, just heavy-handedly.

I've added `add_cppwinrt_projection` which creates a target to link to, and that gives better control and better performance.
